// Package intentv1 defines the Protocol Buffer and gRPC service contracts
// for the AIEN Intent Service.
//
// WHAT IS A PROTOCOL BUFFER?
// ==========================
// Protocol Buffers (protobuf) is a language-neutral, platform-neutral,
// extensible mechanism for serializing structured data. Think of it as a
// more efficient, strongly-typed alternative to JSON.
//
// WHY NOT JUST USE JSON?
// ======================
// 1. Size: Protobuf binary encoding is 3-10x smaller than JSON.
// 2. Speed: Serialization/deserialization is 20-100x faster.
// 3. Schema: The .proto file IS the contract. Both client and server
//    generate code from the same source of truth. No mismatch possible.
// 4. Backward Compatibility: Field numbers (not names) identify fields
//    on the wire. You can rename fields, add new ones, or deprecate old
//    ones without breaking existing clients.
//
// WHAT IS gRPC?
// =============
// gRPC is a high-performance RPC (Remote Procedure Call) framework built
// on top of HTTP/2 and Protocol Buffers. Instead of designing REST endpoints
// and manually parsing JSON, you define service methods in a .proto file
// and gRPC generates both client and server code for you.
//
// WHY gRPC OVER REST?
// ===================
// 1. Strong contracts: The .proto file enforces types at compile time.
// 2. HTTP/2: Multiplexing, header compression, bidirectional streaming.
// 3. Code generation: No hand-written HTTP clients or route handlers.
// 4. Streaming: gRPC natively supports server-streaming, client-streaming,
//    and bidirectional streaming — essential for distributed systems.
//
// TRADE-OFFS:
// ===========
// - gRPC is harder to debug with curl (binary protocol).
//   → That's why our Gateway translates HTTP/JSON → gRPC.
// - Browser support requires gRPC-Web or a proxy.
//   → Our Gateway serves that purpose.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: intent/v1/intent.proto

// The package name creates a namespace for these types.
// Convention: <project>.<service>.<version>

package intentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IntentType enumerates the categories of intents the system can process.
//
// WHY AN ENUM AND NOT A STRING?
// Enums are validated at deserialization time. A typo like "trnasfer"
// would be caught immediately rather than silently accepted and failing
// later during execution. Enums also enable exhaustive switch statements
// in Go, so the compiler warns if you forget to handle a new type.
type IntentType int32

const (
	// Default value. Protobuf 3 requires the first enum value to be 0.
	// We use this as "unspecified" to catch uninitialized fields.
	IntentType_INTENT_TYPE_UNSPECIFIED IntentType = 0
	// A value transfer between two parties.
	IntentType_INTENT_TYPE_TRANSFER IntentType = 1
	// A computation request to be executed on a node.
	IntentType_INTENT_TYPE_COMPUTE IntentType = 2
	// A data query across the distributed network.
	IntentType_INTENT_TYPE_QUERY IntentType = 3
	// A scheduled/recurring intent (cron-like).
	IntentType_INTENT_TYPE_SCHEDULED IntentType = 4
)

// Enum value maps for IntentType.
var (
	IntentType_name = map[int32]string{
		0: "INTENT_TYPE_UNSPECIFIED",
		1: "INTENT_TYPE_TRANSFER",
		2: "INTENT_TYPE_COMPUTE",
		3: "INTENT_TYPE_QUERY",
		4: "INTENT_TYPE_SCHEDULED",
	}
	IntentType_value = map[string]int32{
		"INTENT_TYPE_UNSPECIFIED": 0,
		"INTENT_TYPE_TRANSFER":    1,
		"INTENT_TYPE_COMPUTE":     2,
		"INTENT_TYPE_QUERY":       3,
		"INTENT_TYPE_SCHEDULED":   4,
	}
)

func (x IntentType) Enum() *IntentType {
	p := new(IntentType)
	*p = x
	return p
}

func (x IntentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntentType) Descriptor() protoreflect.EnumDescriptor {
	return file_intent_v1_intent_proto_enumTypes[0].Descriptor()
}

func (IntentType) Type() protoreflect.EnumType {
	return &file_intent_v1_intent_proto_enumTypes[0]
}

func (x IntentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntentType.Descriptor instead.
func (IntentType) EnumDescriptor() ([]byte, []int) {
	return file_intent_v1_intent_proto_rawDescGZIP(), []int{0}
}

// IntentStatus tracks the lifecycle of an intent through the system.
//
// STATE MACHINE:
//
//	PENDING → VALIDATED → SCHEDULED → EXECUTING → COMPLETED
//	                                             → FAILED
//	PENDING → REJECTED (validation failure)
//	Any     → CANCELLED (by submitter)
type IntentStatus int32

const (
	IntentStatus_INTENT_STATUS_UNSPECIFIED IntentStatus = 0
	// Received by the system, awaiting validation.
	IntentStatus_INTENT_STATUS_PENDING IntentStatus = 1
	// Passed validation (signature, constraints, permissions).
	IntentStatus_INTENT_STATUS_VALIDATED IntentStatus = 2
	// Assigned to an execution node by the scheduler.
	IntentStatus_INTENT_STATUS_SCHEDULED IntentStatus = 3
	// Currently being executed on a node.
	IntentStatus_INTENT_STATUS_EXECUTING IntentStatus = 4
	// Execution completed successfully; result committed to ledger.
	IntentStatus_INTENT_STATUS_COMPLETED IntentStatus = 5
	// Execution failed after all retry attempts.
	IntentStatus_INTENT_STATUS_FAILED IntentStatus = 6
	// Rejected during validation (bad signature, violated constraints).
	IntentStatus_INTENT_STATUS_REJECTED IntentStatus = 7
	// Cancelled by the submitter before execution completed.
	IntentStatus_INTENT_STATUS_CANCELLED IntentStatus = 8
)

// Enum value maps for IntentStatus.
var (
	IntentStatus_name = map[int32]string{
		0: "INTENT_STATUS_UNSPECIFIED",
		1: "INTENT_STATUS_PENDING",
		2: "INTENT_STATUS_VALIDATED",
		3: "INTENT_STATUS_SCHEDULED",
		4: "INTENT_STATUS_EXECUTING",
		5: "INTENT_STATUS_COMPLETED",
		6: "INTENT_STATUS_FAILED",
		7: "INTENT_STATUS_REJECTED",
		8: "INTENT_STATUS_CANCELLED",
	}
	IntentStatus_value = map[string]int32{
		"INTENT_STATUS_UNSPECIFIED": 0,
		"INTENT_STATUS_PENDING":     1,
		"INTENT_STATUS_VALIDATED":   2,
		"INTENT_STATUS_SCHEDULED":   3,
		"INTENT_STATUS_EXECUTING":   4,
		"INTENT_STATUS_COMPLETED":   5,
		"INTENT_STATUS_FAILED":      6,
		"INTENT_STATUS_REJECTED":    7,
		"INTENT_STATUS_CANCELLED":   8,
	}
)

func (x IntentStatus) Enum() *IntentStatus {
	p := new(IntentStatus)
	*p = x
	return p
}

func (x IntentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_intent_v1_intent_proto_enumTypes[1].Descriptor()
}

func (IntentStatus) Type() protoreflect.EnumType {
	return &file_intent_v1_intent_proto_enumTypes[1]
}

func (x IntentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntentStatus.Descriptor instead.
func (IntentStatus) EnumDescriptor() ([]byte, []int) {
	return file_intent_v1_intent_proto_rawDescGZIP(), []int{1}
}

// Intent represents a user's declarative request for a state transition.
//
// DESIGN DECISION: Why separate "type" and "payload"?
// In traditional transaction systems, the operation IS the payload.
// In an intent system, the TYPE tells the scheduler what execution
// strategy to use, while the PAYLOAD contains the domain-specific data.
// This separation enables the scheduler to optimize routing without
// parsing application-level data.
type Intent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this intent (UUID v7, time-ordered).
	// WHY UUID v7? Unlike UUID v4 (random), v7 embeds a timestamp,
	// making it naturally sortable. This matters for our append-only
	// ledger — entries are already in chronological order without
	// needing a separate sort.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The type of intent. Determines which execution strategy the
	// scheduler selects.
	Type IntentType `protobuf:"varint,2,opt,name=type,proto3,enum=aien.intent.v1.IntentType" json:"type,omitempty"`
	// Current lifecycle status of this intent.
	Status IntentStatus `protobuf:"varint,3,opt,name=status,proto3,enum=aien.intent.v1.IntentStatus" json:"status,omitempty"`
	// The submitter's identity. In Phase 1, this is a simple string
	// identifier. Later, this becomes an Ed25519 public key.
	SubmitterId string `protobuf:"bytes,4,opt,name=submitter_id,json=submitterId,proto3" json:"submitter_id,omitempty"`
	// The declarative payload describing WHAT the user wants to happen.
	// This is intentionally bytes, not a nested message, because the
	// payload schema varies by IntentType. The intent-service treats
	// this as opaque; only the execution engine interprets it.
	//
	// DESIGN DECISION: Why bytes instead of google.protobuf.Any?
	// google.protobuf.Any requires the receiver to have the type
	// descriptor registered. Using bytes with a known IntentType
	// gives us the same flexibility with simpler deserialization.
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// Constraints the system must honor during execution.
	Constraints *IntentConstraints `protobuf:"bytes,6,opt,name=constraints,proto3" json:"constraints,omitempty"`
	// Cryptographic signature over (type + payload + constraints + submitter_id).
	// This proves the intent was created by the submitter and hasn't
	// been tampered with. Hex encoded string.
	Signature string `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	// The submitter's Ed25519 public key (hex encoded).
	// This acts as the cryptographic identity of the submitter.
	SubmitterPublicKey string `protobuf:"bytes,10,opt,name=submitter_public_key,json=submitterPublicKey,proto3" json:"submitter_public_key,omitempty"`
	// Timestamps managed by the system, not the client.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_intent_v1_intent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_intent_v1_intent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_intent_v1_intent_proto_rawDescGZIP(), []int{0}
}

func (x *Intent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Intent) GetType() IntentType {
	if x != nil {
		return x.Type
	}
	return IntentType_INTENT_TYPE_UNSPECIFIED
}

func (x *Intent) GetStatus() IntentStatus {
	if x != nil {
		return x.Status
	}
	return IntentStatus_INTENT_STATUS_UNSPECIFIED
}

func (x *Intent) GetSubmitterId() string {
	if x != nil {
		return x.SubmitterId
	}
	return ""
}

func (x *Intent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Intent) GetConstraints() *IntentConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *Intent) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Intent) GetSubmitterPublicKey() string {
	if x != nil {
		return x.SubmitterPublicKey
	}
	return ""
}

func (x *Intent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Intent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// IntentConstraints specify the boundaries within which the system
// must execute this intent. These are declarative — the submitter
// says WHAT they want, not HOW to achieve it.
//
// DESIGN DECISION: Why constraints as a separate message?
// Constraints are cross-cutting concerns (deadlines, cost limits,
// priority) that apply regardless of IntentType. Embedding them
// in the payload would force every execution engine to re-implement
// constraint checking. By lifting them into a dedicated message,
// the scheduler can enforce them centrally.
type IntentConstraints struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum time the system has to complete this intent.
	// After this deadline, the intent is marked FAILED.
	Deadline *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// Execution priority. Higher values = higher priority.
	// The scheduler uses this for queue ordering.
	// Range: 0 (lowest) to 10 (highest). Default: 5.
	Priority int32 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	// Maximum number of retry attempts on failure.
	// 0 means no retries. Default: 3.
	MaxRetries int32 `protobuf:"varint,3,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	// If true, the intent is idempotent — safe to re-execute
	// without side effects. This enables aggressive retry
	// and speculative execution strategies.
	Idempotent    bool `protobuf:"varint,4,opt,name=idempotent,proto3" json:"idempotent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentConstraints) Reset() {
	*x = IntentConstraints{}
	mi := &file_intent_v1_intent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentConstraints) ProtoMessage() {}

func (x *IntentConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_intent_v1_intent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentConstraints.ProtoReflect.Descriptor instead.
func (*IntentConstraints) Descriptor() ([]byte, []int) {
	return file_intent_v1_intent_proto_rawDescGZIP(), []int{1}
}

func (x *IntentConstraints) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *IntentConstraints) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *IntentConstraints) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *IntentConstraints) GetIdempotent() bool {
	if x != nil {
		return x.Idempotent
	}
	return false
}

type SubmitIntentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The intent type — tells the system what execution strategy to use.
	Type IntentType `protobuf:"varint,1,opt,name=type,proto3,enum=aien.intent.v1.IntentType" json:"type,omitempty"`
	// The application-level payload.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Execution constraints.
	Constraints *IntentConstraints `protobuf:"bytes,3,opt,name=constraints,proto3" json:"constraints,omitempty"`
	// Submitter identity.
	SubmitterId string `protobuf:"bytes,4,opt,name=submitter_id,json=submitterId,proto3" json:"submitter_id,omitempty"`
	// Cryptographic signature (hex encoded string).
	Signature string `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// Submitter Ed25519 public key (hex encoded).
	SubmitterPublicKey string `protobuf:"bytes,6,opt,name=submitter_public_key,json=submitterPublicKey,proto3" json:"submitter_public_key,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubmitIntentRequest) Reset() {
	*x = SubmitIntentRequest{}
	mi := &file_intent_v1_intent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitIntentRequest) ProtoMessage() {}

func (x *SubmitIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intent_v1_intent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitIntentRequest.ProtoReflect.Descriptor instead.
func (*SubmitIntentRequest) Descriptor() ([]byte, []int) {
	return file_intent_v1_intent_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitIntentRequest) GetType() IntentType {
	if x != nil {
		return x.Type
	}
	return IntentType_INTENT_TYPE_UNSPECIFIED
}

func (x *SubmitIntentRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubmitIntentRequest) GetConstraints() *IntentConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *SubmitIntentRequest) GetSubmitterId() string {
	if x != nil {
		return x.SubmitterId
	}
	return ""
}

func (x *SubmitIntentRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SubmitIntentRequest) GetSubmitterPublicKey() string {
	if x != nil {
		return x.SubmitterPublicKey
	}
	return ""
}

type SubmitIntentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The system-assigned intent ID.
	IntentId string `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	// The initial status (should always be PENDING).
	Status IntentStatus `protobuf:"varint,2,opt,name=status,proto3,enum=aien.intent.v1.IntentStatus" json:"status,omitempty"`
	// When the system received this intent.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitIntentResponse) Reset() {
	*x = SubmitIntentResponse{}
	mi := &file_intent_v1_intent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitIntentResponse) ProtoMessage() {}

func (x *SubmitIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intent_v1_intent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitIntentResponse.ProtoReflect.Descriptor instead.
func (*SubmitIntentResponse) Descriptor() ([]byte, []int) {
	return file_intent_v1_intent_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitIntentResponse) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *SubmitIntentResponse) GetStatus() IntentStatus {
	if x != nil {
		return x.Status
	}
	return IntentStatus_INTENT_STATUS_UNSPECIFIED
}

func (x *SubmitIntentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetIntentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The intent ID to look up.
	IntentId      string `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntentRequest) Reset() {
	*x = GetIntentRequest{}
	mi := &file_intent_v1_intent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntentRequest) ProtoMessage() {}

func (x *GetIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intent_v1_intent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntentRequest.ProtoReflect.Descriptor instead.
func (*GetIntentRequest) Descriptor() ([]byte, []int) {
	return file_intent_v1_intent_proto_rawDescGZIP(), []int{4}
}

func (x *GetIntentRequest) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

type GetIntentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full intent record.
	Intent        *Intent `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntentResponse) Reset() {
	*x = GetIntentResponse{}
	mi := &file_intent_v1_intent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntentResponse) ProtoMessage() {}

func (x *GetIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intent_v1_intent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntentResponse.ProtoReflect.Descriptor instead.
func (*GetIntentResponse) Descriptor() ([]byte, []int) {
	return file_intent_v1_intent_proto_rawDescGZIP(), []int{5}
}

func (x *GetIntentResponse) GetIntent() *Intent {
	if x != nil {
		return x.Intent
	}
	return nil
}

type ListIntentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by status.
	StatusFilter IntentStatus `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=aien.intent.v1.IntentStatus" json:"status_filter,omitempty"`
	// Optional: filter by submitter.
	SubmitterIdFilter string `protobuf:"bytes,2,opt,name=submitter_id_filter,json=submitterIdFilter,proto3" json:"submitter_id_filter,omitempty"`
	// Pagination: maximum number of results to return.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Pagination: token from a previous ListIntentsResponse.
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIntentsRequest) Reset() {
	*x = ListIntentsRequest{}
	mi := &file_intent_v1_intent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIntentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIntentsRequest) ProtoMessage() {}

func (x *ListIntentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intent_v1_intent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIntentsRequest.ProtoReflect.Descriptor instead.
func (*ListIntentsRequest) Descriptor() ([]byte, []int) {
	return file_intent_v1_intent_proto_rawDescGZIP(), []int{6}
}

func (x *ListIntentsRequest) GetStatusFilter() IntentStatus {
	if x != nil {
		return x.StatusFilter
	}
	return IntentStatus_INTENT_STATUS_UNSPECIFIED
}

func (x *ListIntentsRequest) GetSubmitterIdFilter() string {
	if x != nil {
		return x.SubmitterIdFilter
	}
	return ""
}

func (x *ListIntentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListIntentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListIntentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The matching intents.
	Intents []*Intent `protobuf:"bytes,1,rep,name=intents,proto3" json:"intents,omitempty"`
	// Token to pass in the next ListIntentsRequest for pagination.
	// Empty if there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total count of intents matching the filter (before pagination).
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIntentsResponse) Reset() {
	*x = ListIntentsResponse{}
	mi := &file_intent_v1_intent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIntentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIntentsResponse) ProtoMessage() {}

func (x *ListIntentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intent_v1_intent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIntentsResponse.ProtoReflect.Descriptor instead.
func (*ListIntentsResponse) Descriptor() ([]byte, []int) {
	return file_intent_v1_intent_proto_rawDescGZIP(), []int{7}
}

func (x *ListIntentsResponse) GetIntents() []*Intent {
	if x != nil {
		return x.Intents
	}
	return nil
}

func (x *ListIntentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListIntentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_intent_v1_intent_proto protoreflect.FileDescriptor

const file_intent_v1_intent_proto_rawDesc = "" +
	"\n" +
	"\x16intent/v1/intent.proto\x12\x0eaien.intent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x03\n" +
	"\x06Intent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.aien.intent.v1.IntentTypeR\x04type\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.aien.intent.v1.IntentStatusR\x06status\x12!\n" +
	"\fsubmitter_id\x18\x04 \x01(\tR\vsubmitterId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12C\n" +
	"\vconstraints\x18\x06 \x01(\v2!.aien.intent.v1.IntentConstraintsR\vconstraints\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x120\n" +
	"\x14submitter_public_key\x18\n" +
	" \x01(\tR\x12submitterPublicKey\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa8\x01\n" +
	"\x11IntentConstraints\x126\n" +
	"\bdeadline\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vmax_retries\x18\x03 \x01(\x05R\n" +
	"maxRetries\x12\x1e\n" +
	"\n" +
	"idempotent\x18\x04 \x01(\bR\n" +
	"idempotent\"\x97\x02\n" +
	"\x13SubmitIntentRequest\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.aien.intent.v1.IntentTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12C\n" +
	"\vconstraints\x18\x03 \x01(\v2!.aien.intent.v1.IntentConstraintsR\vconstraints\x12!\n" +
	"\fsubmitter_id\x18\x04 \x01(\tR\vsubmitterId\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x120\n" +
	"\x14submitter_public_key\x18\x06 \x01(\tR\x12submitterPublicKey\"\xa4\x01\n" +
	"\x14SubmitIntentResponse\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.aien.intent.v1.IntentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"/\n" +
	"\x10GetIntentRequest\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\"C\n" +
	"\x11GetIntentResponse\x12.\n" +
	"\x06intent\x18\x01 \x01(\v2\x16.aien.intent.v1.IntentR\x06intent\"\xc3\x01\n" +
	"\x12ListIntentsRequest\x12A\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x1c.aien.intent.v1.IntentStatusR\fstatusFilter\x12.\n" +
	"\x13submitter_id_filter\x18\x02 \x01(\tR\x11submitterIdFilter\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x90\x01\n" +
	"\x13ListIntentsResponse\x120\n" +
	"\aintents\x18\x01 \x03(\v2\x16.aien.intent.v1.IntentR\aintents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount*\x8e\x01\n" +
	"\n" +
	"IntentType\x12\x1b\n" +
	"\x17INTENT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INTENT_TYPE_TRANSFER\x10\x01\x12\x17\n" +
	"\x13INTENT_TYPE_COMPUTE\x10\x02\x12\x15\n" +
	"\x11INTENT_TYPE_QUERY\x10\x03\x12\x19\n" +
	"\x15INTENT_TYPE_SCHEDULED\x10\x04*\x8f\x02\n" +
	"\fIntentStatus\x12\x1d\n" +
	"\x19INTENT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15INTENT_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17INTENT_STATUS_VALIDATED\x10\x02\x12\x1b\n" +
	"\x17INTENT_STATUS_SCHEDULED\x10\x03\x12\x1b\n" +
	"\x17INTENT_STATUS_EXECUTING\x10\x04\x12\x1b\n" +
	"\x17INTENT_STATUS_COMPLETED\x10\x05\x12\x18\n" +
	"\x14INTENT_STATUS_FAILED\x10\x06\x12\x1a\n" +
	"\x16INTENT_STATUS_REJECTED\x10\a\x12\x1b\n" +
	"\x17INTENT_STATUS_CANCELLED\x10\b2\x94\x02\n" +
	"\rIntentService\x12Y\n" +
	"\fSubmitIntent\x12#.aien.intent.v1.SubmitIntentRequest\x1a$.aien.intent.v1.SubmitIntentResponse\x12P\n" +
	"\tGetIntent\x12 .aien.intent.v1.GetIntentRequest\x1a!.aien.intent.v1.GetIntentResponse\x12V\n" +
	"\vListIntents\x12\".aien.intent.v1.ListIntentsRequest\x1a#.aien.intent.v1.ListIntentsResponseB8Z6github.com/aien-platform/aien/proto/intent/v1;intentv1b\x06proto3"

var (
	file_intent_v1_intent_proto_rawDescOnce sync.Once
	file_intent_v1_intent_proto_rawDescData []byte
)

func file_intent_v1_intent_proto_rawDescGZIP() []byte {
	file_intent_v1_intent_proto_rawDescOnce.Do(func() {
		file_intent_v1_intent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_intent_v1_intent_proto_rawDesc), len(file_intent_v1_intent_proto_rawDesc)))
	})
	return file_intent_v1_intent_proto_rawDescData
}

var file_intent_v1_intent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_intent_v1_intent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_intent_v1_intent_proto_goTypes = []any{
	(IntentType)(0),               // 0: aien.intent.v1.IntentType
	(IntentStatus)(0),             // 1: aien.intent.v1.IntentStatus
	(*Intent)(nil),                // 2: aien.intent.v1.Intent
	(*IntentConstraints)(nil),     // 3: aien.intent.v1.IntentConstraints
	(*SubmitIntentRequest)(nil),   // 4: aien.intent.v1.SubmitIntentRequest
	(*SubmitIntentResponse)(nil),  // 5: aien.intent.v1.SubmitIntentResponse
	(*GetIntentRequest)(nil),      // 6: aien.intent.v1.GetIntentRequest
	(*GetIntentResponse)(nil),     // 7: aien.intent.v1.GetIntentResponse
	(*ListIntentsRequest)(nil),    // 8: aien.intent.v1.ListIntentsRequest
	(*ListIntentsResponse)(nil),   // 9: aien.intent.v1.ListIntentsResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_intent_v1_intent_proto_depIdxs = []int32{
	0,  // 0: aien.intent.v1.Intent.type:type_name -> aien.intent.v1.IntentType
	1,  // 1: aien.intent.v1.Intent.status:type_name -> aien.intent.v1.IntentStatus
	3,  // 2: aien.intent.v1.Intent.constraints:type_name -> aien.intent.v1.IntentConstraints
	10, // 3: aien.intent.v1.Intent.created_at:type_name -> google.protobuf.Timestamp
	10, // 4: aien.intent.v1.Intent.updated_at:type_name -> google.protobuf.Timestamp
	10, // 5: aien.intent.v1.IntentConstraints.deadline:type_name -> google.protobuf.Timestamp
	0,  // 6: aien.intent.v1.SubmitIntentRequest.type:type_name -> aien.intent.v1.IntentType
	3,  // 7: aien.intent.v1.SubmitIntentRequest.constraints:type_name -> aien.intent.v1.IntentConstraints
	1,  // 8: aien.intent.v1.SubmitIntentResponse.status:type_name -> aien.intent.v1.IntentStatus
	10, // 9: aien.intent.v1.SubmitIntentResponse.created_at:type_name -> google.protobuf.Timestamp
	2,  // 10: aien.intent.v1.GetIntentResponse.intent:type_name -> aien.intent.v1.Intent
	1,  // 11: aien.intent.v1.ListIntentsRequest.status_filter:type_name -> aien.intent.v1.IntentStatus
	2,  // 12: aien.intent.v1.ListIntentsResponse.intents:type_name -> aien.intent.v1.Intent
	4,  // 13: aien.intent.v1.IntentService.SubmitIntent:input_type -> aien.intent.v1.SubmitIntentRequest
	6,  // 14: aien.intent.v1.IntentService.GetIntent:input_type -> aien.intent.v1.GetIntentRequest
	8,  // 15: aien.intent.v1.IntentService.ListIntents:input_type -> aien.intent.v1.ListIntentsRequest
	5,  // 16: aien.intent.v1.IntentService.SubmitIntent:output_type -> aien.intent.v1.SubmitIntentResponse
	7,  // 17: aien.intent.v1.IntentService.GetIntent:output_type -> aien.intent.v1.GetIntentResponse
	9,  // 18: aien.intent.v1.IntentService.ListIntents:output_type -> aien.intent.v1.ListIntentsResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_intent_v1_intent_proto_init() }
func file_intent_v1_intent_proto_init() {
	if File_intent_v1_intent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_intent_v1_intent_proto_rawDesc), len(file_intent_v1_intent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_intent_v1_intent_proto_goTypes,
		DependencyIndexes: file_intent_v1_intent_proto_depIdxs,
		EnumInfos:         file_intent_v1_intent_proto_enumTypes,
		MessageInfos:      file_intent_v1_intent_proto_msgTypes,
	}.Build()
	File_intent_v1_intent_proto = out.File
	file_intent_v1_intent_proto_goTypes = nil
	file_intent_v1_intent_proto_depIdxs = nil
}
