// Package intentv1 defines the Protocol Buffer and gRPC service contracts
// for the AIEN Intent Service.
//
// WHAT IS A PROTOCOL BUFFER?
// ==========================
// Protocol Buffers (protobuf) is a language-neutral, platform-neutral,
// extensible mechanism for serializing structured data. Think of it as a
// more efficient, strongly-typed alternative to JSON.
//
// WHY NOT JUST USE JSON?
// ======================
// 1. Size: Protobuf binary encoding is 3-10x smaller than JSON.
// 2. Speed: Serialization/deserialization is 20-100x faster.
// 3. Schema: The .proto file IS the contract. Both client and server
//    generate code from the same source of truth. No mismatch possible.
// 4. Backward Compatibility: Field numbers (not names) identify fields
//    on the wire. You can rename fields, add new ones, or deprecate old
//    ones without breaking existing clients.
//
// WHAT IS gRPC?
// =============
// gRPC is a high-performance RPC (Remote Procedure Call) framework built
// on top of HTTP/2 and Protocol Buffers. Instead of designing REST endpoints
// and manually parsing JSON, you define service methods in a .proto file
// and gRPC generates both client and server code for you.
//
// WHY gRPC OVER REST?
// ===================
// 1. Strong contracts: The .proto file enforces types at compile time.
// 2. HTTP/2: Multiplexing, header compression, bidirectional streaming.
// 3. Code generation: No hand-written HTTP clients or route handlers.
// 4. Streaming: gRPC natively supports server-streaming, client-streaming,
//    and bidirectional streaming — essential for distributed systems.
//
// TRADE-OFFS:
// ===========
// - gRPC is harder to debug with curl (binary protocol).
//   → That's why our Gateway translates HTTP/JSON → gRPC.
// - Browser support requires gRPC-Web or a proxy.
//   → Our Gateway serves that purpose.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.0
// source: intent/v1/intent.proto

// The package name creates a namespace for these types.
// Convention: <project>.<service>.<version>

package intentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IntentService_SubmitIntent_FullMethodName = "/aien.intent.v1.IntentService/SubmitIntent"
	IntentService_GetIntent_FullMethodName    = "/aien.intent.v1.IntentService/GetIntent"
	IntentService_ListIntents_FullMethodName  = "/aien.intent.v1.IntentService/ListIntents"
)

// IntentServiceClient is the client API for IntentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IntentService is the core gRPC service for managing intents.
//
// WHY THESE THREE RPCS?
// This follows the principle of starting with the minimum viable API.
// SubmitIntent is the write path. GetIntent and ListIntents are the
// read path. We can add UpdateIntent, CancelIntent, StreamIntents
// later without breaking existing clients (protobuf backward compat).
type IntentServiceClient interface {
	// SubmitIntent accepts a new intent from a client.
	// The service validates the intent, assigns it an ID, persists it,
	// and returns the ID to the client.
	SubmitIntent(ctx context.Context, in *SubmitIntentRequest, opts ...grpc.CallOption) (*SubmitIntentResponse, error)
	// GetIntent retrieves a single intent by its ID.
	GetIntent(ctx context.Context, in *GetIntentRequest, opts ...grpc.CallOption) (*GetIntentResponse, error)
	// ListIntents returns a paginated list of intents, optionally
	// filtered by status or submitter.
	ListIntents(ctx context.Context, in *ListIntentsRequest, opts ...grpc.CallOption) (*ListIntentsResponse, error)
}

type intentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntentServiceClient(cc grpc.ClientConnInterface) IntentServiceClient {
	return &intentServiceClient{cc}
}

func (c *intentServiceClient) SubmitIntent(ctx context.Context, in *SubmitIntentRequest, opts ...grpc.CallOption) (*SubmitIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitIntentResponse)
	err := c.cc.Invoke(ctx, IntentService_SubmitIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intentServiceClient) GetIntent(ctx context.Context, in *GetIntentRequest, opts ...grpc.CallOption) (*GetIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIntentResponse)
	err := c.cc.Invoke(ctx, IntentService_GetIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intentServiceClient) ListIntents(ctx context.Context, in *ListIntentsRequest, opts ...grpc.CallOption) (*ListIntentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIntentsResponse)
	err := c.cc.Invoke(ctx, IntentService_ListIntents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntentServiceServer is the server API for IntentService service.
// All implementations must embed UnimplementedIntentServiceServer
// for forward compatibility.
//
// IntentService is the core gRPC service for managing intents.
//
// WHY THESE THREE RPCS?
// This follows the principle of starting with the minimum viable API.
// SubmitIntent is the write path. GetIntent and ListIntents are the
// read path. We can add UpdateIntent, CancelIntent, StreamIntents
// later without breaking existing clients (protobuf backward compat).
type IntentServiceServer interface {
	// SubmitIntent accepts a new intent from a client.
	// The service validates the intent, assigns it an ID, persists it,
	// and returns the ID to the client.
	SubmitIntent(context.Context, *SubmitIntentRequest) (*SubmitIntentResponse, error)
	// GetIntent retrieves a single intent by its ID.
	GetIntent(context.Context, *GetIntentRequest) (*GetIntentResponse, error)
	// ListIntents returns a paginated list of intents, optionally
	// filtered by status or submitter.
	ListIntents(context.Context, *ListIntentsRequest) (*ListIntentsResponse, error)
	mustEmbedUnimplementedIntentServiceServer()
}

// UnimplementedIntentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntentServiceServer struct{}

func (UnimplementedIntentServiceServer) SubmitIntent(context.Context, *SubmitIntentRequest) (*SubmitIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitIntent not implemented")
}
func (UnimplementedIntentServiceServer) GetIntent(context.Context, *GetIntentRequest) (*GetIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIntent not implemented")
}
func (UnimplementedIntentServiceServer) ListIntents(context.Context, *ListIntentsRequest) (*ListIntentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIntents not implemented")
}
func (UnimplementedIntentServiceServer) mustEmbedUnimplementedIntentServiceServer() {}
func (UnimplementedIntentServiceServer) testEmbeddedByValue()                       {}

// UnsafeIntentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntentServiceServer will
// result in compilation errors.
type UnsafeIntentServiceServer interface {
	mustEmbedUnimplementedIntentServiceServer()
}

func RegisterIntentServiceServer(s grpc.ServiceRegistrar, srv IntentServiceServer) {
	// If the following call panics, it indicates UnimplementedIntentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntentService_ServiceDesc, srv)
}

func _IntentService_SubmitIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentServiceServer).SubmitIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntentService_SubmitIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentServiceServer).SubmitIntent(ctx, req.(*SubmitIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntentService_GetIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentServiceServer).GetIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntentService_GetIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentServiceServer).GetIntent(ctx, req.(*GetIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntentService_ListIntents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIntentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentServiceServer).ListIntents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntentService_ListIntents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentServiceServer).ListIntents(ctx, req.(*ListIntentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntentService_ServiceDesc is the grpc.ServiceDesc for IntentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aien.intent.v1.IntentService",
	HandlerType: (*IntentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitIntent",
			Handler:    _IntentService_SubmitIntent_Handler,
		},
		{
			MethodName: "GetIntent",
			Handler:    _IntentService_GetIntent_Handler,
		},
		{
			MethodName: "ListIntents",
			Handler:    _IntentService_ListIntents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "intent/v1/intent.proto",
}
