// Package handler implements the gRPC IntentService defined in proto/intent/v1.
//
// SEPARATION OF CONCERNS
// ======================
// This package contains ONLY the gRPC handler logic:
// 1. Receive a gRPC request.
// 2. Validate the request.
// 3. Delegate to the Store for persistence.
// 4. Return a gRPC response.
//
// It does NOT contain:
// - Storage logic (that's in the store package).
// - HTTP translation (that's in the gateway).
// - Business rules like scheduling (that's in the scheduler, Phase 2).
//
// This separation means we can test the handler with a mock store,
// and we can swap the store without touching handler code.
package handler

import (
	"context"
	"log/slog"

	"github.com/aien-platform/aien/intent-service/store"
	"github.com/aien-platform/aien/shared/crypto"

	intentv1 "github.com/aien-platform/aien/proto/intent/v1"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// IntentHandler implements the IntentServiceServer interface
// generated by protoc-gen-go-grpc.
//
// DESIGN PATTERN: Dependency Injection
// The handler receives its dependencies (store, logger) through
// its constructor, not by creating them internally. This means:
// 1. Tests can inject a mock store.
// 2. The handler doesn't know or care if it's talking to
//    an in-memory map or PostgreSQL.
type IntentHandler struct {
	// Embed the unimplemented server to satisfy the interface.
	// This is a protobuf convention: if we add new RPCs to the
	// proto later, this prevents compilation errors until we
	// implement them. It returns "Unimplemented" for any RPC
	// we haven't written yet.
	intentv1.UnimplementedIntentServiceServer

	store     store.Store
	logger    *slog.Logger
}

// New creates a new IntentHandler with the given dependencies.
//
// In production Go code, constructors are typically named "New"
// (not "NewIntentHandler") when the package name already provides
// context. Callers write: handler.New(store, logger)
func New(s store.Store, logger *slog.Logger) *IntentHandler {
	return &IntentHandler{
		store:     s,
		logger:    logger,
	}
}

// SubmitIntent handles the SubmitIntent RPC.
//
// gRPC PATTERNS:
// - We return (response, nil) on success.
// - We return (nil, status.Error(code, msg)) on failure.
// - gRPC status codes map to HTTP codes:
//   codes.InvalidArgument → 400 Bad Request
//   codes.NotFound        → 404 Not Found
//   codes.Internal        → 500 Internal Server Error
//
// WHY status.Errorf AND NOT fmt.Errorf?
// gRPC clients can inspect the error CODE programmatically:
//   if status.Code(err) == codes.NotFound { ... }
// A plain error would always map to codes.Unknown.
func (h *IntentHandler) SubmitIntent(ctx context.Context, req *intentv1.SubmitIntentRequest) (*intentv1.SubmitIntentResponse, error) {
	h.logger.Info("SubmitIntent called",
		"type", req.Type.String(),
		"submitter", req.SubmitterId,
	)

	// --- Validation ---
	// In production systems, validation is the first thing you do.
	// Fail fast, fail clearly. Don't let bad data propagate deeper
	// into the system where errors become harder to diagnose.
	if req.Type == intentv1.IntentType_INTENT_TYPE_UNSPECIFIED {
		return nil, status.Errorf(codes.InvalidArgument, "intent type is required")
	}
	if req.SubmitterId == "" {
		return nil, status.Errorf(codes.InvalidArgument, "submitter_id is required")
	}
	if req.SubmitterPublicKey == "" {
		return nil, status.Errorf(codes.InvalidArgument, "submitter_public_key is required")
	}
	if req.Signature == "" {
		return nil, status.Errorf(codes.InvalidArgument, "signature is required")
	}

	// --- Cryptographic Signature Verification ---
	//
	// We verify that the signature was generated by the private key corresponding
	// to the provided submitter_public_key, and that the payload has not been tampered.
	signBytes := crypto.GetSignBytes(req.Type.String(), req.SubmitterId, req.Payload)
	isValid, err := crypto.Verify(signBytes, req.Signature, req.SubmitterPublicKey)
	if err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "failed to decode signature or public key: %v", err)
	}
	if !isValid {
		h.logger.Warn("Signature verification failed", "submitter", req.SubmitterId, "key", req.SubmitterPublicKey)
		return nil, status.Errorf(codes.Unauthenticated, "invalid cryptographic signature")
	}

	// --- Persistence ---
	intent, err := h.store.Create(ctx, req)
	if err != nil {
		h.logger.Error("Failed to create intent", "error", err)
		return nil, status.Errorf(codes.Internal, "failed to create intent: %v", err)
	}

	h.logger.Info("Intent created successfully (delegated to transactional outbox)",
		"id", intent.Id,
		"status", intent.Status.String(),
	)

	return &intentv1.SubmitIntentResponse{
		IntentId:  intent.Id,
		Status:    intent.Status,
		CreatedAt: intent.CreatedAt,
	}, nil
}

// GetIntent handles the GetIntent RPC.
func (h *IntentHandler) GetIntent(ctx context.Context, req *intentv1.GetIntentRequest) (*intentv1.GetIntentResponse, error) {
	h.logger.Info("GetIntent called", "id", req.IntentId)

	if req.IntentId == "" {
		return nil, status.Errorf(codes.InvalidArgument, "intent_id is required")
	}

	intent, err := h.store.Get(ctx, req.IntentId)
	if err != nil {
		h.logger.Warn("Intent not found", "id", req.IntentId)
		return nil, status.Errorf(codes.NotFound, "intent not found: %s", req.IntentId)
	}

	return &intentv1.GetIntentResponse{
		Intent: intent,
	}, nil
}

// ListIntents handles the ListIntents RPC.
func (h *IntentHandler) ListIntents(ctx context.Context, req *intentv1.ListIntentsRequest) (*intentv1.ListIntentsResponse, error) {
	h.logger.Info("ListIntents called",
		"status_filter", req.StatusFilter.String(),
		"submitter_filter", req.SubmitterIdFilter,
		"page_size", req.PageSize,
	)

	intents, nextToken, total, err := h.store.List(
		ctx,
		req.StatusFilter,
		req.SubmitterIdFilter,
		int(req.PageSize),
		req.PageToken,
	)
	if err != nil {
		h.logger.Error("Failed to list intents", "error", err)
		return nil, status.Errorf(codes.Internal, "failed to list intents: %v", err)
	}

	h.logger.Info("ListIntents returning", "count", len(intents), "total", total)

	return &intentv1.ListIntentsResponse{
		Intents:       intents,
		NextPageToken: nextToken,
		TotalCount:    int32(total),
	}, nil
}
